/* Formatted on 4/6/2022 11:40:21 AM (QP5 v5.215.12089.38647) */
SELECT UT.NUM_ROWS, UTC.COLUMN_NAME, UT.NUM_ROWS - UTC.NUM_NULLS
  FROM    USER_TABLES UT
       INNER JOIN
          USER_TAB_COLUMNS UTC
       ON UT.TABLE_NAME = UTC.TABLE_NAME
 WHERE     UT.TABLE_NAME = 'STG_DATA_ADAMS';