/* Formatted on 5/19/2022 10:45:10 AM (QP5 v5.215.12089.38647) */
SELECT UP.V_USR_ID,
       UG.V_GROUP_CODE,
       RM.V_ROLE_NAME,
       RM.V_ROLE_DESC,
       FM.V_FUNCTION_DESC,
       FM.V_FUNCTION_NAME
  FROM CSSMS_USR_PROFILE UP
       INNER JOIN CSSMS_USR_GROUP_MAP UG
          ON UG.V_USR_ID = UP.V_USR_ID
       INNER JOIN CSSMS_GROUP_ROLE_MAP GP
          ON GP.V_GROUP_CODE = UG.V_GROUP_CODE
       INNER JOIN CSSMS_ROLE_MAST RM
          ON RM.V_ROLE_CODE = GP.V_ROLE_CODE
       INNER JOIN CSSMS_ROLE_FUNCTION_MAP RF
          ON RF.V_ROLE_CODE = RM.V_ROLE_CODE
       INNER JOIN CSSMS_FUNCTION_MAST FM
          ON FM.V_FUNCTION_CODE = RF.V_FUNCTION_CODE
 WHERE UP.V_USR_ID = 'TLXERM' AND RF.V_FUNCTION_CODE LIKE '%PLC%'