/* Formatted on 4/2/2022 10:49:57 PM (QP5 v5.215.12089.38647) */
  SELECT A.N_ACCT_SKEY V_ACCOUNT_NUMBER,
         D_CASH_FLOW_DATE,
         N_CASH_FLOW_BUCKET_ID,
         N_PRINCIPAL_RUN_OFF,
         N_INTEREST_RUN_OFF,
         N_CASH_FLOW_AMOUNT,
         N_CASH_SHORTFALL,
         N_CASH_SHORTFALL_PV,
         N_DISCOUNT_RATE,
         N_DISCOUNT_FACTOR,
         NULL N_IFRS_STAGE_SKEY,
         N_LGD_PERCENT,
         N_CUMULATIVE_IMPAIRED_PROB,
         A.N_DISCOUNT_FACTOR,
         A.N_CUMULATIVE_LOSS_RATE,
         A.N_EXPECTED_CASH_FLOW_RATE,
         A.N_EXPECTED_CASH_FLOW,
         A.N_CASH_SHORTFALL,
         A.N_CASH_SHORTFALL_PV
    FROM FSI_CF_PROCESS_OUTPUTS A
   WHERE A.N_RUN_SKEY = 2200 AND A.N_ACCT_SKEY IN (3220)
ORDER BY N_CASH_FLOW_BUCKET_ID;