/* Formatted on 4/2/2022 10:50:42 PM (QP5 v5.215.12089.38647) */
  SELECT N_ACCT_SKEY, N_CASH_FLOW_BUCKET_ID, N_PRINCIPAL_RUN_OFF
    FROM FSI_CF_PROCESS_OUTPUTS A
   WHERE A.N_RUN_SKEY = 2200 AND N_PRINCIPAL_RUN_OFF < 0
ORDER BY N_ACCT_SKEY, N_CASH_FLOW_BUCKET_ID;


  SELECT N_ACCT_SKEY, N_CASH_FLOW_BUCKET_ID, N_PRINCIPAL_RUN_OFF
    FROM FSI_CF_PROCESS_OUTPUTS A
   WHERE A.N_RUN_SKEY = 2200                    -- AND N_PRINCIPAL_RUN_OFF < 0
                            AND N_ACCT_SKEY = 1865
ORDER BY N_ACCT_SKEY, N_CASH_FLOW_BUCKET_ID;