/* Formatted on 4/2/2022 10:56:13 PM (QP5 v5.215.12089.38647) */
SELECT *
  FROM VW_IFRS_GL_LEVEL_DATA
 WHERE V_DATA_ORIGIN = 'FLEXCUBE' AND SIGN <> 1;

SELECT V_PROD_cODE,
       N_EOP_BAL,
       V_CCY_CODE,
       V_BROKERAGE_FIRM,
       SI.V_ACCOUNT_NUMBER
  FROM STG_INVESTMENTS SI
 WHERE FIC_MIS_dATE = '30-SEP-2021' AND V_PROD_cODE = '40203001';                                                                                                                                                                            --AND V_BROKERAGE_FIRM = 'VW_IFRS_ADJUSTMENTS_MANUAL' ;

SELECT *
  FROM VW_IFRS_ADJUSTMENTS_MANUAL
 WHERE     FIC_MIS_DATE = '30-SEP-2021'
       AND V_PROD_cODE IN ('40104001', '40101001', '40203001', '40402009');

DELETE FROM STG_INVESTMENTS
      WHERE V_BROKERAGE_FIRM = 'VW_IFRS_ADJUSTMENTS_MANUAL';


MERGE INTO STG_INVESTMENTS TRG
     USING OFSRECON.AATB_STG_FWD_EXCHG_RATES FWD
        ON (    FWD.FIC_MIS_DATE = TRG.FIC_MIS_DATE
            AND FWD.V_FROM_CCY_CODE = TRG.V_CCY_CODE
            AND FWD.V_TO_CCY_CODE = 'PKR'
            AND TRG.FIC_MIS_DATE = '30-SEP-2021'
            AND TRG.V_BROKERAGE_FIRM = 'VW_IFRS_GL_LEVEL_DATA')
WHEN MATCHED
THEN
   UPDATE SET TRG.N_EOP_BAL = TRG.N_EOP_BAL * FWD.N_EXCHANGE_RATE;

   --TRG.V_CCY_CODE = 'PKR'

UPDATE STG_INVESTMENTS SI
   SET SI.V_CCY_CODE = 'PKR'
 WHERE     SI.FIC_MIS_DATE = '30-SEP-2021'
       AND SI.V_BROKERAGE_FIRM = 'VW_IFRS_GL_LEVEL_DATA';


SELECT v_account_number,
       v_prod_Code,
       v_data_origin,
       n_eop_bal
  FROM STG_INVESTMENTS trg
 WHERE     TRG.FIC_MIS_DATE = '30-SEP-2021'
       AND TRG.V_BROKERAGE_FIRM = 'VW_IFRS_GL_LEVEL_DATA';