CREATE TABLE FSI_M_TP_REPLICATING_PORTFOLIO_20220530 AS SELECT * FROM FSI_M_TP_REPLICATING_PORTFOLIO;

CREATE TABLE FSI_D_CASA_20220530 AS SELECT * FROM FSI_D_CASA;

CREATE TABLE FSI_D_INVESTMENTS_20220530 AS  SELECT * FROM FSI_D_INVESTMENTS ;

CREATE TABLE FSI_D_TERM_DEPOSITS_20220530 AS SELECT * FROM FSI_D_TERM_DEPOSITS;

CREATE TABLE FSI_D_CREDIT_CARDS_20220530 AS SELECT * FROM FSI_D_CREDIT_CARDS;

CREATE TABLE FSI_D_LOAN_CONTRACTS_20220530 AS SELECT * FROM FSI_D_LOAN_CONTRACTS ;

CREATE TABLE FCT_FTP_ACCOUNT_SUMMARY_20220530 AS SELECT * FROM FCT_FTP_ACCOUNT_SUMMARY;
