SELECT PV.N_MARKET_ID,
         SUM (PV.N_BASE_PV),
         SUM (PV.N_SIM_PRESENT_VALUE),
         SUM (PV.N_PROFIT_LOSS_AMOUNT)
    FROM FSI_MR_TRADE_SIMULATED_PV_DTL PV
   WHERE PV.N_BSNS_DEFN_EXECN_ID = 1645005385429  --business execution id
GROUP BY N_MARKET_ID
ORDER BY N_MARKET_ID DESC