    SELECT :L_FIC_MIS_DATE AS FIC_MIS_DATE,
             'PIBs' AS V_INSTRUMENT_TYPE,
             NVL (MPO.N_VAR_RCY, 0) AS N_STANDALONE_VAR, MPO.N_BSNS_DEFN_EXECN_ID ,
             2 AS N_ORDER
        FROM FSI_MR_PORTFOLIO_OUTPUTS MPO
             INNER JOIN FSI_MR_PORT_RISK_BSNS_DEFN MBD
                ON MPO.N_BUSINESS_DEFN_ID = MBD.N_BUSINESS_DEFN_ID
             INNER JOIN FSI_MR_PORT_RISK_EXECN_DTLS ED
                ON     MPO.N_BSNS_DEFN_EXECN_ID = ED.N_BSNS_DEFN_EXECN_ID
                   AND ED.F_REPORTING_FLAG = 'Y'
                   AND ED.V_BSNS_EXECN_STATUS = 'SUCCESS'
       WHERE     MPO.N_BUSS_APPROACH_TYPE_ID = 200288
             AND MBD.V_BUSINESS_DEFN_NAME = 'Historical_1Day_horizon_99_CL'
             AND MPO.N_AS_OF_DATE_SKEY = TO_CHAR (:L_FIC_MIS_DATE, 'YYYYMMDD')
    