SELECT * FROM STG_MR_SCRIPTS_SCHEDULE
WHERE '08-JAN-2022' > d_FROM_dATE AND 
'08-JAN-2022' < D_TO_DATE  ;


update STG_INVESTMENTS SI
SET SI.N_COUPON_RATE = REC.N_COUPON_RATE,
SI.N_COUPON_FREQUENCY = 0.5
WHERE V_aCCOUNT_NUMBER = REC.V_ACCOUNT_NUMBER
AND FIC_MIS_dATE = MIS_dATE;



--D_FROM_dATE >= '08-JAN-2022' or 
--D_TO_DATE > '08-JAN-2022';


grant ALL ON STG_MR_SCRIPTS_SCHEDULE TO OFSMRMM