/* Formatted on 4/2/2022 11:09:52 PM (QP5 v5.215.12089.38647) */
SELECT DISTINCT RD.V_RATING_cODE
  FROM    STG_ACCOUNT_RATING_DETAILS RD
       INNER JOIN
          STG_INVESTMENTS SI
       ON     SI.FIC_MIS_DATE = RD.FIC_MIS_DATE
          AND SI.V_ACCOUNT_NUMBER = RD.V_ACCOUNT_NUMBER
 WHERE SI.FIC_MIS_dATE = '30-SEP-2021';


 --AND V_ACCOUNT_NUMBER = 'GURCOR-3883-AKLCS00012'

SELECT (SL.V_ACCOUNT_NUMBER) AS V_ACCOUNT_NO,
       SS.V_RATING_CODE,
       SS.V_RATING_SRC_CODE,
       SL.FIC_MIS_DATE
  FROM    STG_INVESTMENTS SL
       INNER JOIN
          VW_STG_BNK_ACCT_RATING SS
       ON     SS.V_ACCOUNT_NO =
                 CASE
                    WHEN LENGTH (SL.V_ACCOUNT_NUMBER) >= 24
                    THEN
                       SUBSTR (SL.V_ACCOUNT_NUMBER, 10, 24)
                    ELSE
                       SL.V_ACCOUNT_NUMBER
                 END
          AND SL.FIC_MIS_DATE = SS.FIC_MIS_DATE;



  SELECT COUNT (*), si.v_brokerage_firm
    FROM    STG_INVESTMENTS SI
         INNER JOIN
            OFSBASEL.STG_ACCOUNT_RATING_DETAILS RD
         ON SI.V_ACCOUNT_NUMBER = RD.V_ACCOUNT_NUMBER
   WHERE SI.FIC_MIS_DATE = '30-SEP-2021'
GROUP BY si.v_brokerage_firm;

 --and rd.V_RATING_CODE IS NULL;

  SELECT COUNT (*), V_BROKERAGE_FIRM
    FROM STG_INVESTMENTS SI
   WHERE SI.FIC_MIS_DATE = '30-SEP-2021'
GROUP BY V_BROKERAGE_FIRM;

SELECT *
  FROM OFSBASEL.STG_ACCOUNT_RATING_DETAILS
 WHERE FIC_MIS_DATE = '30-SEP-2021';

SELECT *
  FROM OFSRECON.STG_BNK_GL_RATING
 WHERE FIC_MIS_dATE = '30-SEP-2021';

  SELECT FIC_MIS_dATE, COUNT (*)
    FROM VW_POP_STG_BNK_GL_RATING
GROUP BY FIC_MIS_dATE;